// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  
  // Not: "seed" kasıtlı olarak tanımlı değil. Bu sayede `prisma migrate dev`
  // ve `prisma migrate reset` artık otomatik olarak prisma/seed.js çalıştırmaz.
  // Seed verisi istenirse elle çalıştırılabilir: node prisma/seed.js
  migrations: {
    path: "prisma/migrations",
  },


  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
